apiVersion: v1
kind: ConfigMap
metadata:
  name: tknopik-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: componentconfig/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: tknopik-scheduler
    algorithmSource:
      policy:
        configMap:
          namespace: kube-system
          name: tknopik-scheduler-policy
    leaderElection:
      leaderElect: true
      lockObjectName: tknopik-scheduler
      lockObjectNamespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tknopik-scheduler-policy
  namespace: kube-system
data:
  policy.cfg : |
    {
      "kind" : "Policy",
      "apiVersion" : "v1",
      "predicates" : [
        {"name" : "PodFitsHostPorts"},
        {"name" : "PodFitsResources"},
        {"name" : "NoDiskConflict"},
        {"name" : "MatchNodeSelector"},
        {"name" : "HostName"}
      ],
      "priorities" : [
        {"name" : "LeastRequestedPriority", "weight" : 1},
        {"name" : "BalancedResourceAllocation", "weight" : 1},
        {"name" : "ServiceSpreadingPriority", "weight" : 1},
        {"name" : "EqualPriority", "weight" : 1}
      ],
      "extenders" : [{
        "urlPrefix": "http://localhost:8080/scheduler",
        "filterVerb": "filter",
        "prioritizeVerb": "prioritize",
        "preemptVerb": "preemption",
        "bindVerb": "",
        "weight": 1,
        "enableHttps": false,
        "nodeCacheCapable": false
      }],
      "hardPodAffinitySymmetricWeight" : 10
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tknopik-scheduler
  namespace: kube-system
  labels:
    app: tknopik-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tknopik-scheduler
  template:
    metadata:
      labels:
        app: tknopik-scheduler
        version: 0.0.34
    spec:
      volumes:
        - name: tknopik-scheduler-config
          configMap:
            name: tknopik-scheduler-config
      containers:
        - name: tknopik-scheduler-ctr
          image: gcr.io/google_containers/hyperkube:v1.11.1
          imagePullPolicy: IfNotPresent
          args:
            - kube-scheduler
            - --config=/tknopik-scheduler/config.yaml
            - -v=4
          volumeMounts:
            - name: tknopik-scheduler-config
              mountPath: /tknopik-scheduler
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
        - name: tknopik-scheduler-extender-ctr
          image: knopt/k8s-ext:0905
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /version
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /version
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
      serviceAccount: admin-user
