apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-metrics
rules:
- apiGroups:
    - metrics.k8s.io
  resources:
    - pods
    - nodes
  verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-metrics-rolebinding
subjects:
- kind: ServiceAccount
  name: user
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view-metrics
  apiGroup: rbac.authorization.k8s.io
