apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpustress-deployment
  namespace: kube-system
  labels:
    app: cpustress-app
spec:
  selector:
    matchLabels:
      app: cpustress-app
  template:
    metadata:
      name: cpustress-dist-DATE
      namespace: cpustress
      labels:
        app: cpustress-app
      annotations:
        dist: "DIST-PLACEHOLDER"
    spec:
      schedulerName: tknopik-scheduler
      containers:
        - name: cpustress-containter
          image: knopt/scipy:2604
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
#              memory: "200Mi"
            requests:
              cpu: "0.01"
#              memory: "100Mi"
          command: ["python3"]
          args: ["stresscpu.py", "--window-size", "1m", "--dist", "DIST-PLACEHOLDER", "--timeout", "8m"]
