apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpustress-deployment
  namespace: kube-system
  labels:
    app: cpustress-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cpustress-app
  template:
    metadata:
      name: cpustress-dist-DATE
      namespace: cpustress
      labels:
        app: cpustress-app
      annotations:
        dist: "DIST-PLACEHOLDER"
    spec:
      schedulerName: tknopik-scheduler
      containers:
        - name: cpustress-containter
          image: knopt/scipy:250401
          imagePullPolicy: IfNotPresent
#          resources:
#            limits:
#              cpu: "0.4"
#              memory: "200Mi"
#            requests:
#              cpu: "0.2"
#              memory: "100Mi"
          command: ["python3"]
          args: ["stresscpu.py", "--window-size", "1m", "--dist", "DIST-PLACEHOLDER", "--timeout", "4m"]
