apiVersion: v1
kind: Pod
metadata:
  name: cpustress-dist-DATE
  namespace: cpustress
  labels:
    app: cpustress-dist
  annotations:
    dist: "DIST-PLACEHOLDER"
spec:
  schedulerName: tknopik-scheduler
  restartPolicy: OnFailure
  containers:
    - name: cpustress-containter
      image: knopt/scipy:2604
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1.0"
        requests:
          cpu: "0.01"
      command: ["python3"]
      args: ["stresscpu.py", "--window-size", "1m", "--dist", "DIST-PLACEHOLDER", "--timeout", "8m"]
