apiVersion: v1
kind: Pod
metadata:
  name: cpustress-dist
  namespace: cpustress-namespace
  labels:
    app: cpustress-dist
  annotations:
    dist: "DIST-PLACEHOLDER"
spec:
  schedulerName: my-scheduler
  containers:
  - name: cpustress-containter
    image: knopt/scipy:1804
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "2.0"
        memory: "100Mi"
      requests:
        cpu: "1.0"
        memory: "50Mi"
    command: ["python3"]
    args: ["stresscpu.py", "--window-size", "1m", "--dist", "DIST-PLACEHOLDER"]
