apiVersion: v1
kind: Pod
metadata:
  name: cpustress-uni-50
  namespace: cpustress-namespace
spec:
  schedulerName: my-scheduler
  containers:
  - name: cpustress-containter
    image: knopt/scipy:1804
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "1.0"
        memory: "400Mi"
      requests:
        cpu: "0.5"
        memory: "300Mi"
    command: ["python3"]
    args: ["stresscpu.py", "--cpu-load", "0.5", "--dist", "uniform", "--window-size", "3s"]

