apiVersion: v1
kind: Pod
metadata:
  name: cpustress-const-50
  namespace: cpustress-namespace
  labels:
    app: cpustress-const
spec:
  schedulerName: my-scheduler
  containers:
  - name: cpustress-containter
    image: knopt/scipy:1804
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "1.0"
        memory: "500Mi"
      requests:
        cpu: "0.5"
        memory: "300Mi"
    command: ["python3"]
    args: ["stresscpu.py", "--cpu-load", "0.5", "--dist", "const"]
