apiVersion: v1
kind: Pod
metadata:
  name: cpustress-const-50
  namespace: cpustress
  labels:
    app: cpustress-const
spec:
  schedulerName: my-scheduler
  containers:
  - name: cpustress-containter
    image: knopt/scipy:1804
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "2.0"
        memory: "100Mi"
      requests:
        cpu: "1.0"
        memory: "50Mi"
    command: ["python3"]
    args: ["stresscpu.py", "--cpu-load", "1", "--dist", "const"]
