apiVersion: v1
kind: Pod
metadata:
  name: memstress-1300m-1-name
  namespace: memstress-namespace
spec:
  containers:
  - name: memstress-1300m-1-containter
    image: lorel/docker-stress-ng
    resources:
      limits:
        memory: "1900Mi"
      requests:
        memory: "1300Mi"
    command: ["stress-ng"]
    args: ["--vm", "1", "--vm-bytes", "1300M", "--timeout", "1h"]

